namespace ProtonDrive.App.Mapping;

public enum MappingErrorCode
{
    None,
    DriveAccessFailed,
    DriveVolumeDiverged,
    DriveShareDiverged,
    DriveHostDeviceDiverged,
    DriveFolderDoesNotExist,
    DriveFolderDiverged,
    RemoteSharedWithMeItemDoesNotExist,
    RemoteSharedWithMeItemPermissionsDiverged,
    LocalFileSystemAccessFailed,
    LocalVolumeNotSupported,
    LocalFolderDoesNotExist,
    LocalFolderDiverged,
    LocalAndRemoteFoldersNotEmpty,
    LocalFolderNotEmpty,
    LocalFolderIncludedByAnAlreadySyncedFolder,
    LocalFolderIncludesAnAlreadySyncedFolder,
    LocalFolderNonSyncable,
    OnDemandSyncRootNotRegistered,
    OnDemandSyncRootMissingSyncRootFlag,
    ConflictingOnDemandSyncRootExists,
    ConflictingDescendantOnDemandSyncRootExists,
    InsufficientLocalFreeSpace,
    InsufficientDeviceQuota,
    SharingDisabled,
    PhotosNotReady,
    PhotosDisabled,
    PhotoImportFailed,
}
